# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20160311_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='down_votes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='up_votes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='down_votes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='up_votes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
